### ISSUE TITLE
How many milliseconds does the GC run once in V8 generally?

### ISSUE THREAD

**Issue by MrStronger** [aliyun-node/v8-gc-log-parser#1]

**Comment by joyeecheung** [comment]
That depends on how big your heap is, how it's divided, which version of V8 it is, what parameters that you have passed to V8, what kind of memory activity the application incurs, .etc...lots of parameters.

**Comment by MrStronger** [comment]
Thanks :)

**Comment by joyeecheung** [comment]
There were actually some discussions around providing performance profiles for typical applications wrt. throughput, latency, CPU & memory usage, GC overhead... during this year's Node.js diagnostics summit. You can watch https://github.com/nodejs/diagnostics to know about the work being done in the working group.
